# Student Computer Lab Toolkit
# <Insider Preview> (dev 85acb2bc17b4681498fadfe32a84f4d56b7b3822)
# 本文件编码为 UTF-8。
[crack_restore]
crack_when_launching: true
hijack_image: true
suspend_process: true
[window]
forced_show: true
random_title: true
[custom_rules]
