# Student Computer Lab Toolkit - Legacy Edition
#  (main 4e475a6ee4c20f02b9825c6597e06cc2018148a4)
# 本文件编码为 UTF-8。
[crack_restore]
crack_when_launching: true
hijack_image: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
