# Student Computer Lab Toolkit
# <Insider Preview> (dev 8ac1c321b8bbfbb5199a3c789c4d18f3aee236f6)
# 本文件编码为 UTF-8。
[crack_restore]
crack_when_launching: true
hijack_image: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
