# Student Computer Lab Toolkit - Mainline Edition
# <Insider Preview> (dev eff8bf6ae83f9d16a8018b38845123ffe8ef25d4)
# UTF-8 编码
[crack_restore]
crack_when_launching: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
