# Student Computer Lab Toolkit - Legacy Edition
# <Insider Preview> (dev 94cd7e11d33e3172c09c9f08b1a87612490f84ca)
# UTF-8 编码
[crack_restore]
crack_when_launching: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
