# Student Computer Lab Toolkit - Mainline Edition
# <Insider Preview> (dev dc51454d90266e412f8b9c620654243766b54fc2)
# UTF-8 编码
[crack_restore]
crack_when_launching: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
