# Student Computer Lab Toolkit
# <Insider Preview> (dev 40c05b00ae75b70368a462bf9cdb07d745946830)
# 本文件编码为 UTF-8。
[crack_restore]
crack_when_launching: true
hijack_image: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
