# Student Computer Lab Toolkit - Mainline Edition
# <Insider Preview> (dev 5a73f654328436af6c9b8bf9120ed158ccd5f66f)
# 本文件编码为 UTF-8。
[crack_restore]
crack_when_launching: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
