# Student Computer Lab Toolkit - Mainline Edition
# v7.2.0-preview (dev e188ecfed9e093512db31072137bc43b90c6a02f)
# UTF-8 编码
[crack_restore]
crack_when_launching: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
