# Student Computer Lab Toolkit - Mainline Edition
# <Insider Preview> (dev 8008c2731d3dfa9e2aaffaad43b5979412f5e215)
# UTF-8 编码
[crack_restore]
crack_when_launching: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
