# Student Computer Lab Toolkit
# <Insider Preview> (dev fa4c04cdcb805b7e89adb6206656c497a2394fbb)
# 本文件编码为 UTF-8。
[crack_restore]
crack_when_launching: true
hijack_image: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
