# Student Computer Lab Toolkit - Mainline Edition
# <Insider Preview> (dev 26485ff3588a58f9dd30867c42632000e1a78a22)
# UTF-8 编码
[crack_restore]
crack_when_launching: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
