# Student Computer Lab Toolkit - Legacy Edition
# <Insider Preview> (dev e76a87ef8a10489f29804f60ddb5a7020b299bbd)
# UTF-8 编码
[crack_restore]
crack_when_launching: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
