# Student Computer Lab Toolkit
# <Insider Preview> (dev ec021ca54a67352050daba40a3ec9c89c57d8880)
# 本文件编码为 UTF-8。
[crack_restore]
crack_when_launching: true
hijack_image: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
